version: "3.7"

services:
  robot-challenge:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: robot-challenge
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run build
